// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF-l4LQTqtUW4EH_TKi0Wi9miDoYwpYkc',
    appId: '1:1086081570110:web:2cbb7937da745f7571886f',
    messagingSenderId: '1086081570110',
    projectId: 'videoplayerapp-f7dc9',
    authDomain: 'videoplayerapp-f7dc9.firebaseapp.com',
    storageBucket: 'videoplayerapp-f7dc9.appspot.com',
    measurementId: 'G-JHK2419T03',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxOIjZHyHgnjqfkORF2ELW3Vv6MkLA3rE',
    appId: '1:1086081570110:android:3326dc702b3dd4df71886f',
    messagingSenderId: '1086081570110',
    projectId: 'videoplayerapp-f7dc9',
    storageBucket: 'videoplayerapp-f7dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwY8Ajw6eHqn0tCLwR_wcccL6qvqCc9A0',
    appId: '1:1086081570110:ios:aae8ed4287739b8871886f',
    messagingSenderId: '1086081570110',
    projectId: 'videoplayerapp-f7dc9',
    storageBucket: 'videoplayerapp-f7dc9.appspot.com',
    iosBundleId: 'com.example.videoplayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwY8Ajw6eHqn0tCLwR_wcccL6qvqCc9A0',
    appId: '1:1086081570110:ios:aae8ed4287739b8871886f',
    messagingSenderId: '1086081570110',
    projectId: 'videoplayerapp-f7dc9',
    storageBucket: 'videoplayerapp-f7dc9.appspot.com',
    iosBundleId: 'com.example.videoplayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCF-l4LQTqtUW4EH_TKi0Wi9miDoYwpYkc',
    appId: '1:1086081570110:web:398d5b61d399280e71886f',
    messagingSenderId: '1086081570110',
    projectId: 'videoplayerapp-f7dc9',
    authDomain: 'videoplayerapp-f7dc9.firebaseapp.com',
    storageBucket: 'videoplayerapp-f7dc9.appspot.com',
    measurementId: 'G-W3RE4RJY7G',
  );
}
